# Signal types: 
# 1)sine, 
# 2)square, 
# 3)sawtooth

signal1:
  type: 1 
  amplitude: 2
  frequency: 5
  offset: 0

signal2:
  type: 2
  amplitude: 0.5
  frequency: 1
  offset: 2

signal3:
  type: 3
  amplitude: 1
  frequency: 0.5
  offset: 1

signal4:
  type: 1
  amplitude: 0.5
  frequency: 0.1
  offset: -2

signal5:
  type: 2
  amplitude: 3
  frequency: 2
  offset: 0